In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
Mushrooms = pd.read_csv('mushrooms.csv')

In [3]:
Mushrooms.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [4]:
Mushrooms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
class                       8124 non-null object
cap-shape                   8124 non-null object
cap-surface                 8124 non-null object
cap-color                   8124 non-null object
bruises                     8124 non-null object
odor                        8124 non-null object
gill-attachment             8124 non-null object
gill-spacing                8124 non-null object
gill-size                   8124 non-null object
gill-color                  8124 non-null object
stalk-shape                 8124 non-null object
stalk-root                  8124 non-null object
stalk-surface-above-ring    8124 non-null object
stalk-surface-below-ring    8124 non-null object
stalk-color-above-ring      8124 non-null object
stalk-color-below-ring      8124 non-null object
veil-type                   8124 non-null object
veil-color                  8124 non-null object
ring-number

In [5]:
Mushrooms.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
count          8124      8124       8124   ...                       8124   
unique            2         2         12   ...                          4   
top               c         b          b   ...                          s   
freq           6812      5612       1728   ...                       4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

In [6]:
columns = list(Mushrooms)
for i in columns:
    Mushrooms[i] = Mushrooms[i].astype('category')

In [7]:
Mushrooms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
class                       8124 non-null category
cap-shape                   8124 non-null category
cap-surface                 8124 non-null category
cap-color                   8124 non-null category
bruises                     8124 non-null category
odor                        8124 non-null category
gill-attachment             8124 non-null category
gill-spacing                8124 non-null category
gill-size                   8124 non-null category
gill-color                  8124 non-null category
stalk-shape                 8124 non-null category
stalk-root                  8124 non-null category
stalk-surface-above-ring    8124 non-null category
stalk-surface-below-ring    8124 non-null category
stalk-color-above-ring      8124 non-null category
stalk-color-below-ring      8124 non-null category
veil-type                   8124 non-null category
veil-color                

In [8]:
Mushrooms_X = Mushrooms.drop('class', axis=1)

In [9]:
Mushrooms_X.head()

cap-shape cap-surface cap-color bruises odor gill-attachment gill-spacing  \
0         x           s         n       t    p               f            c   
1         x           s         y       t    a               f            c   
2         b           s         w       t    l               f            c   
3         x           y         w       t    p               f            c   
4         x           s         g       f    n               f            w   

  gill-size gill-color stalk-shape   ...   stalk-surface-below-ring  \
0         n          k           e   ...                          s   
1         b          k           e   ...                          s   
2         b          n           e   ...                          s   
3         n          n           e   ...                          s   
4         b          k           t   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 22 columns]

In [10]:
Mushrooms_Y = Mushrooms['class'].map({'e': 0, 'p': 1})

In [149]:
Mushrooms_X_onehot = Mushrooms_X.copy()
columns = list(Mushrooms_X)
for i in columns:
    Mushrooms_X_onehot = pd.get_dummies(Mushrooms_X_onehot, columns=[i], 
                                        prefix=[i], drop_first=True)

In [12]:
Mushrooms_X_onehot.head()

cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  cap-shape_x  \
0            0            0            0            0            1   
1            0            0            0            0            1   
2            0            0            0            0            0   
3            0            0            0            0            1   
4            0            0            0            0            1   

   cap-surface_g  cap-surface_s  cap-surface_y  cap-color_c  cap-color_e  \
0              0              1              0            0            0   
1              0              1              0            0            0   
2              0              1              0            0            0   
3              0              0              1            0            0   
4              0              1              0            0            0   

     ...      population_n  population_s  population_v  population_y  \
0    ...                 0             1             0             0   
1    ...                 1             0             0             0   
2    ...                 1             0             0             0   
3    ...                 0             1             0             0   
4    ...                 0             0             0             0   

   habitat_g  habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0          0          0          0          0          1          0  
1          1          0          0          0          0          0  
2          0          0          1          0          0          0  
3          0          0          0          0          1          0  
4          1          0          0          0          0          0  

[5 rows x 95 columns]

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
 X_train, X_test, y_train, y_test = train_test_split(Mushrooms_X_onehot, Mushrooms_Y, test_size=0.25, random_state=42, shuffle=True)

In [15]:
from sklearn.linear_model import LogisticRegressionCV

In [16]:
LRCV = LogisticRegressionCV(cv=5, random_state=0, multi_class='multinomial', scoring='recall').fit(X_train, y_train)

In [17]:
LRCV.score(X_train, y_train)

1.0

In [18]:
predictions = LRCV.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix

In [20]:
print(confusion_matrix(y_test, predictions))

[[1040    0]
 [   0  991]]


In [45]:
from sklearn.ensemble import ExtraTreesClassifier

In [46]:
ETCF = ExtraTreesClassifier()

In [47]:
ETCF.fit(X_train, y_train)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [54]:
ETCF.feature_importances_.argmax()

22

In [49]:
predictions = ETCF.predict(X_test)

In [50]:
print(confusion_matrix(y_test, predictions))

[[1040    0]
 [   0  991]]


In [55]:
X_train.columns[22]

'odor_n'

In [56]:
import_features = ETCF.feature_importances_

In [57]:
import_features

array([3.17453013e-04, 9.29947260e-04, 9.41424942e-05, 0.00000000e+00,
       3.33953353e-04, 1.26305081e-04, 1.09545333e-02, 6.93017800e-04,
       4.43582471e-04, 3.40381358e-03, 4.34730223e-05, 7.07134405e-03,
       6.62198199e-04, 0.00000000e+00, 0.00000000e+00, 1.16426268e-03,
       6.62444753e-03, 9.25587172e-02, 5.91310592e-03, 2.36647744e-02,
       5.34952276e-03, 6.50247141e-04, 1.84507670e-01, 2.62205009e-02,
       6.11641922e-03, 9.72959692e-03, 0.00000000e+00, 1.19202608e-02,
       7.46025245e-02, 0.00000000e+00, 3.78133129e-04, 2.03600371e-03,
       2.76621054e-05, 4.50189313e-03, 0.00000000e+00, 6.01425409e-04,
       9.31990329e-04, 5.00980501e-05, 2.33462749e-03, 1.80311343e-03,
       5.31427948e-03, 1.20319359e-02, 1.55980075e-02, 3.21683371e-02,
       2.99370881e-03, 7.61761030e-03, 3.52823294e-02, 0.00000000e+00,
       3.41525080e-03, 5.58489280e-02, 6.99318462e-03, 0.00000000e+00,
       0.00000000e+00, 1.60385339e-04, 0.00000000e+00, 0.00000000e+00,
      

In [140]:
import_features = ETCF.feature_importances_
imp_col = []
for i in range(5):
    j = import_features.argmax()
    imp_col.append(X_train.columns[j])
    import_features[j]=0
print(imp_col)

['odor_n', 'bruises_t', 'gill-size_n', 'spore-print-color_h', 'stalk-surface-below-ring_s']


In [141]:
X_train_reduced = pd.DataFrame()
X_test_reduced = pd.DataFrame()
for col in imp_col:
    X_train_reduced[col] = X_train[col]
for col in imp_col:
    X_test_reduced[col] = X_test[col]

In [150]:
Logreg = LogisticRegressionCV()
Logreg.fit(X_train_reduced,y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv=None, dual=False,
           fit_intercept=True, intercept_scaling=1.0, max_iter=100,
           multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
           refit=True, scoring=None, solver='lbfgs', tol=0.0001, verbose=0)

In [143]:
predictions = Logreg.predict(X_test_reduced)

In [144]:
print(confusion_matrix(y_test, predictions))

[[994  46]
 [ 18 973]]


In [145]:
from sklearn.metrics import classification_report

In [146]:
print(classification_report(y_test, predictions))

             precision    recall  f1-score   support

          0       0.98      0.96      0.97      1040
          1       0.95      0.98      0.97       991

avg / total       0.97      0.97      0.97      2031



In [148]:
X_train_reduced.columns

Index(['odor_n', 'bruises_t', 'gill-size_n', 'spore-print-color_h',
       'stalk-surface-below-ring_s'],
      dtype='object')